# Generated by Django 5.2 on 2025-04-29 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_iamge',
            new_name='profile_image',
        ),
    ]
